site_name: Dataex Client API
repo_url: https://github.com/nzahasan/dataex-client/tree/master
copyright: Copyright &copy; 2021 RIMES

theme:
  name: material
  custom_dir: overrides
  logo: small_logo.svg
  favicon: favicon.png
  palette:
    primary: white
    accent: light blue
  icon:
   admonition: 
     warning: octicons/alert-16
   repo: fontawesome/brands/github


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      
      
nav:
 - Home: 'index.md'
 - Quick Start: 'quick_start.md'
 - Guide:
   - Initilize dataex auth:
      - 'Create dataex auth json file' : 'user-guide/dataex_init.md'  
   - Countries:
      - 'List countries': 'user-guide/dataex_list_country_info.md'
   - Stations: 
      - 'List stations': 'user-guide/dataex_obs_station_list.md'
   - Observations: 
      - 'Download parameter list': 'user-guide/dataex_obs_parameter_list.md'
      - 'Upload observation data': 'user-guide/dataex_insert_obs_data.md'
      - 'Download observation data': 'user-guide/dataex_get_obs_data.md'
      - 'Get observation data summary': 'user-guide/dataex_obs_data_summary.md'

   - Forecasts:
      - 'Download netcdf data': 'user-guide/dataex_netcdf_subset.md'
   - Analysis:
      - 'List reducer names': 'user-guide/dataex_list_reducers.md'
      - 'List forecast analysis user assets': 'user-guide/dataex_list_user_assets.md'
      - 'Download region specific forecast time series': 'user-guide/dataex_region_data_analysis.md'
   
  






   
   
